version: "3.3"
services:
  web:
    image: mental/authorization
    build: .
    ports:
      - "8080:10030"
    links:
      - cont_postgresql
    depends_on:
      - cont_postgresql
    environment:
      SPRING_PROFILES_ACTIVE: default
  cont_postgresql:
    image: sameersbn/postgresql
    ports:
      - "5432:5432"
    environment:
      DB_NAME: authorization-dev,authorization-qa
      DB_USER: dbuser
      DB_PASS: 12345